name: CI

on:
  push:
    branches: [ main ]
  pull_request:
  schedule:
    # Run test on Monday and Thursday at 4:23 UTC
    - cron: "23 4 * * 1,4"

jobs:
  test:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python: [ "3.6", "3.7", "3.8", "3.9" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install package
        run: pip install .[dev]

      - name: Run linters
        run: make lint

      - name: Run unit tests
        run: make unit
